name: 👋 Hello GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "👋 Hello, TVATDCI! This is your first GitHub Action running!"
